---
abstract: 'A glimpse at an Enlightened Perl (CLI Tools).'
author:
  - 'Chris Prather <chris@prather.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Kensho-CLI
no_index:
  directory:
    - inc
    - t
requires:
  App::Ack: 0
  App::Nopaste: 0
  App::perlbrew: 0
  Devel::REPL: 0
  Module::CoreList: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.29
